run_env: DEV # DEV, TEST, STAGING or PROD
server_secret_key: 'ServerKey'
sql_alchemy:
  create_tables: True
  database_uri:  'sqlite:///:memory:'
  track_modifications: False
elasticsearch:
  host: 'https://www.ebi.ac.uk/chembl/glados-es'
run_jobs: False
admin_username: 'admin'
admin_password: '123456'
lsf_submission:
  id_rsa_file: '~/.ssh/id_rsa'
  lsf_user: 'lsf_user'
  lsf_host: 'lsf_host'
generate_default_config: True
job_statistics:
  dry_run: False # If true, do not attempt to save anything, just print it to the debug log. False by default
  general_statistics_index: 'chembl_delayed_jobs_job_record'
